### ISSUE TITLE
test failure in 1.3.0 Errno::ENOENT: No such file or directory @ rb_sysopen - /home/pravi/forge/debian/git/pkg-ruby-extras/ruby-saml/test/responses/invalids/encrypted_new_attack.xml.base64

### ISSUE THREAD

**Issue by pravi** [onelogin/ruby-saml#338]
```
 1) Error:
attack#test_0001_should not be valid:
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/pravi/forge/debian/git/pkg-ruby-extras/ruby-saml/test/responses/invalids/encrypted_new_attack.xml.base64
    /home/pravi/forge/debian/git/pkg-ruby-extras/ruby-saml/test/test_helper.rb:41:in `read'
    /home/pravi/forge/debian/git/pkg-ruby-extras/ruby-saml/test/test_helper.rb:41:in `read_invalid_response'
    /home/pravi/forge/debian/git/pkg-ruby-extras/ruby-saml/test/response_test.rb:1295:in `block (2 levels) in <class:RubySamlTest>'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:108:in `block (3 levels) in run'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:205:in `capture_exceptions'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:105:in `block (2 levels) in run'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:256:in `time_it'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:104:in `block in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:331:in `on_signal'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:276:in `with_info_handler'
    /usr/lib/ruby/vendor_ruby/minitest/test.rb:103:in `run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:778:in `run_one_method'
    /usr/lib/ruby/vendor_ruby/minitest.rb:305:in `run_one_method'
    /usr/lib/ruby/vendor_ruby/minitest.rb:293:in `block (2 levels) in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:292:in `each'
    /usr/lib/ruby/vendor_ruby/minitest.rb:292:in `block in run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:331:in `on_signal'
    /usr/lib/ruby/vendor_ruby/minitest.rb:318:in `with_info_handler'
    /usr/lib/ruby/vendor_ruby/minitest.rb:291:in `run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:152:in `block in __run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:152:in `map'
    /usr/lib/ruby/vendor_ruby/minitest.rb:152:in `__run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:129:in `run'
    /usr/lib/ruby/vendor_ruby/minitest.rb:56:in `block in autorun'

```

**Comment by pitbulk** [comment]
I made the gem with a wrong response_test.rb.

Fixed at [1.3.1](https://rubygems.org/gems/ruby-saml/versions/1.3.1)
