### ISSUE TITLE
Creating AuthRequests with nil RelayState sends empty RelayState URL param

### ISSUE THREAD

**Issue by vincentwoo** [onelogin/ruby-saml#437]
Doing `OneLogin::RubySaml::Authrequest.new.create(settings, RelayState: nil)` still creates an empty RelayState url param. Ideally nil (or perhaps even falsy) RelayState would cause `ruby-saml` to not output a param. This caused an issue for a customer integration recently. SimpleSaml (the PHP library) apparently decided that we had an improperly signed request with the empty param.

**Comment by pitbulk** [comment]
We should definitely avoid to generate TX with empty RelayState URL parameters.

When we generate the [url_string](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/authrequest.rb#L67) we use the [build_query](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/utils.rb#L70) that [doesn't add the RelayState](https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/utils.rb#L74) parameter if there is no content.

but the issue is after that, at the
```
params.each_pair do |key, value|
    request_params[key] = value.to_s
end
```
where params has the RelayState value, so if null set a null value for that parameter to request_params.

Similar issue happens at LogoutRequest and LogoutResponse

@vincentwoo are you able to provide a PR to fix that?

**Comment by vincentwoo** [comment]
I spent about 2m trying to get a branch going but it looks like your tests are completely broken for me on 2.5.0. If you can fix this situation I can try to make a PR, but I don't have the time to debug your test infrastructure.

```ruby
Vincents-MacBook-Pro:ruby-saml vwoo$ rake test
/Users/vwoo/.rubies/ruby-2.5.0/bin/ruby -w -I"lib:lib:test" -I"/Users/vwoo/.rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib" "/Users/vwoo/.rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/rake_test_loader.rb" "test/idp_metadata_parser_test.rb" "test/logging_test.rb" "test/logoutrequest_test.rb" "test/logoutresponse_test.rb" "test/metadata_test.rb" "test/request_test.rb" "test/response_test.rb" "test/saml_message_test.rb" "test/settings_test.rb" "test/slo_logoutrequest_test.rb" "test/slo_logoutresponse_test.rb" "test/utils_test.rb" "test/xml_security_test.rb"
/Users/vwoo/.gem/ruby/2.5.0/gems/timecop-0.6.0/lib/timecop/time_extensions.rb:67: warning: method redefined; discarding old now
/Users/vwoo/.gem/ruby/2.5.0/gems/timecop-0.6.0/lib/timecop/time_stack_item.rb:158: warning: mismatched indentations at 'end' with 'class' at 1
/Users/vwoo/ruby-saml/lib/onelogin/ruby-saml/saml_message.rb:77: warning: shadowing outer local variable - error
/Users/vwoo/ruby-saml/lib/onelogin/ruby-saml/utils.rb:35: warning: character class has duplicated range: /[\n\r\s]/
/Users/vwoo/ruby-saml/lib/onelogin/ruby-saml/utils.rb:54: warning: character class has duplicated range: /[\n\r\s]/
/Users/vwoo/ruby-saml/lib/onelogin/ruby-saml/utils.rb:143: warning: shadowing outer local variable - status_code
/Users/vwoo/ruby-saml/lib/onelogin/ruby-saml/logoutresponse.rb:243: warning: shadowing outer local variable - idp_cert
/Users/vwoo/ruby-saml/lib/xml_security.rb:213: warning: assigned but unused variable - e
/Users/vwoo/ruby-saml/lib/xml_security.rb:256: warning: assigned but unused variable - e
/Users/vwoo/ruby-saml/lib/xml_security.rb:320: warning: assigned but unused variable - uri
/Users/vwoo/ruby-saml/lib/xml_security.rb:95: warning: method redefined; discarding old uuid
/Users/vwoo/ruby-saml/lib/xml_security.rb:196: warning: method redefined; discarding old signed_element_id
/Users/vwoo/ruby-saml/lib/onelogin/ruby-saml/slo_logoutrequest.rb:297: warning: shadowing outer local variable - idp_cert
/Users/vwoo/ruby-saml/lib/onelogin/ruby-saml/response.rb:169: warning: `+' after local variable or literal is interpreted as binary operator
/Users/vwoo/ruby-saml/lib/onelogin/ruby-saml/response.rb:169: warning: even though it seems like unary operator
/Users/vwoo/ruby-saml/lib/onelogin/ruby-saml/response.rb:218: warning: shadowing outer local variable - node
/Users/vwoo/ruby-saml/lib/onelogin/ruby-saml/response.rb:287: warning: assigned but unused variable - doc
/Users/vwoo/ruby-saml/lib/onelogin/ruby-saml/attribute_service.rb:19: warning: `&' interpreted as argument prefix
/Users/vwoo/ruby-saml/test/logoutrequest_test.rb:17: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/logoutrequest_test.rb:20: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/logoutrequest_test.rb:25: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/logoutrequest_test.rb:28: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/logoutrequest_test.rb:39: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/logoutrequest_test.rb:51: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/logoutrequest_test.rb:58: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/logoutrequest_test.rb:67: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:16: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:25: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:38: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:44: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:48: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:54: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:63: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:69: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:78: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:84: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:92: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:98: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:106: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:112: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:120: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:121: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:126: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:129: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:136: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:145: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:152: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:158: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:159: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:165: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:166: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:173: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:174: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/request_test.rb:180: warning: ambiguous first argument; put parentheses or a space even after `/' operator
/Users/vwoo/ruby-saml/test/response_test.rb:336: warning: assigned but unused variable - error_msg
/Users/vwoo/ruby-saml/test/response_test.rb:381: warning: assigned but unused variable - error_msg
/Users/vwoo/ruby-saml/test/response_test.rb:1021: warning: assigned but unused variable - attrs
/Users/vwoo/ruby-saml/test/response_test.rb:1241: warning: assigned but unused variable - response
/Users/vwoo/ruby-saml/test/response_test.rb:1245: warning: assigned but unused variable - response2
/Users/vwoo/ruby-saml/test/response_test.rb:1263: warning: assigned but unused variable - response
/Users/vwoo/ruby-saml/test/response_test.rb:1357: warning: assigned but unused variable - decrypted
/Users/vwoo/ruby-saml/test/settings_test.rb:164: warning: assigned but unused variable - certificates
/Users/vwoo/ruby-saml/test/slo_logoutrequest_test.rb:174: warning: ambiguous first argument; put parentheses or a space even after `/' operator

File does not exist: timecop

Traceback (most recent call last):
	16: from /Users/vwoo/.gem/ruby/2.5.0/gems/simplecov-0.9.2/lib/simplecov/defaults.rb:54:in `block in <top (required)>'
	15: from /Users/vwoo/.gem/ruby/2.5.0/gems/simplecov-0.9.2/lib/simplecov/configuration.rb:158:in `block in at_exit'
	14: from /Users/vwoo/.gem/ruby/2.5.0/gems/simplecov-0.9.2/lib/simplecov.rb:48:in `result'
	13: from /Users/vwoo/.gem/ruby/2.5.0/gems/simplecov-0.9.2/lib/simplecov/result_merger.rb:73:in `store_result'
	12: from /Users/vwoo/.gem/ruby/2.5.0/gems/simplecov-0.9.2/lib/simplecov/result_merger.rb:73:in `open'
	11: from /Users/vwoo/.gem/ruby/2.5.0/gems/simplecov-0.9.2/lib/simplecov/result_merger.rb:78:in `block in store_result'
	10: from /Users/vwoo/.gem/ruby/2.5.0/gems/simplecov-0.9.2/lib/simplecov/result_merger.rb:78:in `open'
	 9: from /Users/vwoo/.gem/ruby/2.5.0/gems/simplecov-0.9.2/lib/simplecov/result_merger.rb:79:in `block (2 levels) in store_result'
	 8: from /Users/vwoo/.gem/ruby/2.5.0/gems/simplecov-0.9.2/lib/simplecov/json.rb:20:in `dump'
	 7: from /Users/vwoo/.gem/ruby/2.5.0/gems/multi_json-1.13.1/lib/multi_json.rb:139:in `dump'
	 6: from /Users/vwoo/.gem/ruby/2.5.0/gems/multi_json-1.13.1/lib/multi_json.rb:133:in `current_adapter'
	 5: from /Users/vwoo/.gem/ruby/2.5.0/gems/multi_json-1.13.1/lib/multi_json.rb:73:in `adapter'
	 4: from /Users/vwoo/.gem/ruby/2.5.0/gems/multi_json-1.13.1/lib/multi_json.rb:91:in `use'
	 3: from /Users/vwoo/.gem/ruby/2.5.0/gems/multi_json-1.13.1/lib/multi_json.rb:103:in `load_adapter'
	 2: from /Users/vwoo/.gem/ruby/2.5.0/gems/multi_json-1.13.1/lib/multi_json.rb:101:in `load_adapter'
	 1: from /Users/vwoo/.gem/ruby/2.5.0/gems/multi_json-1.13.1/lib/multi_json.rb:157:in `load_adapter_from_string_name'
/Users/vwoo/.gem/ruby/2.5.0/gems/multi_json-1.13.1/lib/multi_json.rb:157:in `require': Did not recognize your adapter specification (cannot load such file -- multi_json/adapters/json_gem). (MultiJson::AdapterError)
rake aborted!
Command failed with status (1): [ruby -w -I"lib:lib:test" -I"/Users/vwoo/.rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib" "/Users/vwoo/.rubies/ruby-2.5.0/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/rake_test_loader.rb" "test/idp_metadata_parser_test.rb" "test/logging_test.rb" "test/logoutrequest_test.rb" "test/logoutresponse_test.rb" "test/metadata_test.rb" "test/request_test.rb" "test/response_test.rb" "test/saml_message_test.rb" "test/settings_test.rb" "test/slo_logoutrequest_test.rb" "test/slo_logoutresponse_test.rb" "test/utils_test.rb" "test/xml_security_test.rb" ]

Tasks: TOP => test
(See full trace by running task with --trace)
```

**Comment by vincentwoo** [comment]
Scratch last comment, got tests working w/ bundle exec
